USE Team2_CallumE;

CREATE TABLE Auth_Roles(
	RoleID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    Role_Name VARCHAR(70) NOT NULL,
    PRIMARY KEY(RoleID)
);

CREATE TABLE Users(
	UserID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    Email VARCHAR(100) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    RoleID SMALLINT UNSIGNED NOT NULL,
    PRIMARY KEY(UserID),
    CONSTRAINT FK_RoleUser FOREIGN KEY(RoleID)
    REFERENCES Auth_Roles(RoleID)
);

CREATE TABLE Capabilities(
	CapabilityID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    Name VARCHAR(70) NOT NULL,
    PRIMARY KEY(CapabilityID)
);

CREATE TABLE Families(
	FamilyID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    Name VARCHAR(70) NOT NULL,
    CapabilityID SMALLINT UNSIGNED NOT NULL,
    PRIMARY KEY(FamilyID),
    CONSTRAINT FK_CapabilityFamily FOREIGN KEY(CapabilityID)
    REFERENCES Capabilities(CapabilityID)
    ON DELETE CASCADE
);

CREATE TABLE Bands(
	BandID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    Name VARCHAR(70) NOT NULL,
    Level TINYINT UNSIGNED NOT NULL,
    Training_Available TEXT,
    Competencies TEXT,
    PRIMARY KEY(BandID)
);

CREATE TABLE Job_Role(
	RoleID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    Name VARCHAR(70) NOT NULL,
    Job_Spec TEXT NOT NULL,
    Responsibilities TEXT NOT NULL,
    Sharepoint_Link VARCHAR(255),
    CapabilityID SMALLINT UNSIGNED NOT NULL,
    BandID SMALLINT UNSIGNED NOT NULL,
    FamilyID SMALLINT UNSIGNED NOT NULL,
    PRIMARY KEY(RoleID),
    CONSTRAINT FK_CapabilityRole FOREIGN KEY(CapabilityID)
    REFERENCES Capabilities(CapabilityID)
    ON DELETE CASCADE,
    CONSTRAINT FK_FamilyRole FOREIGN KEY(FamilyID)
    REFERENCES Families(FamilyID)
    ON DELETE CASCADE,
    CONSTRAINT FK_BandRole FOREIGN KEY(BandID)
    REFERENCES Bands(BandID)
    ON DELETE CASCADE
);